name: organization nodejs ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: setup nodejs version - 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: install dependencies
      run: npm install

    - name: unit testing
      run: npm test --if-present

    - name: install dependencies
      run: npm run coverage --if-present
      
       
